import Head from 'next/head'
import ListPost from '../components/ListPost/ListPost'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Post Something!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Post something!
        </h1>
        <ListPost />
        <form className={styles.wrapperForm}>
          <input className={styles.textBox}/>
          <button>
            Submit
          </button>
        </form>
      </main>
    </div>
  )
}
