import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Post Something!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Post something!
        </h1>
        <ul>
          <li>
            <h2>Test building Next JS</h2>
            <p>3/12/2021</p>
          </li>
        </ul>
        <form className={styles.wrapperForm}>
          <input className={styles.textBox}/>
          <button>
            Submit
          </button>
        </form>
      </main>
    </div>
  )
}
